In [28]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [29]:
data=pd.read_csv(r"C:\Users\priya\Desktop\ipcs\pandas\ML\Excel\breast-cancer.csv")
data.head()

,id,radius_mean,perimeter_mean,area_mean,concavity_mean,concave points_mean,fractal_dimension_mean,radius_worst,perimeter_worst,area_worst,concavity_worst,fractal_dimension_worst,diagnosis
0,842302,17.99,122.80,1001.0,0.3001,0.14710,0.07871,25.38,184.60,2019.0,0.7119,0.11890,M
1,842517,20.57,132.90,1326.0,0.0869,0.07017,0.05667,24.99,158.80,1956.0,0.2416,0.08902,M
2,84300903,19.69,130.00,1203.0,0.1974,0.12790,0.05999,23.57,152.50,1709.0,0.4504,0.08758,M
3,84348301,11.42,77.58,386.1,0.2414,0.10520,0.09744,14.91,98.87,567.7,0.6869,0.17300,M
4,84358402,20.29,135.10,1297.0,0.1980,0.10430,0.05883,22.54,152.20,1575.0,0.4000,0.07678,M

In [30]:
data.drop("id",axis=1,inplace=True)
data.head()

,radius_mean,perimeter_mean,area_mean,concavity_mean,concave points_mean,fractal_dimension_mean,radius_worst,perimeter_worst,area_worst,concavity_worst,fractal_dimension_worst,diagnosis
0,17.99,122.80,1001.0,0.3001,0.14710,0.07871,25.38,184.60,2019.0,0.7119,0.11890,M
1,20.57,132.90,1326.0,0.0869,0.07017,0.05667,24.99,158.80,1956.0,0.2416,0.08902,M
2,19.69,130.00,1203.0,0.1974,0.12790,0.05999,23.57,152.50,1709.0,0.4504,0.08758,M
3,11.42,77.58,386.1,0.2414,0.10520,0.09744,14.91,98.87,567.7,0.6869,0.17300,M
4,20.29,135.10,1297.0,0.1980,0.10430,0.05883,22.54,152.20,1575.0,0.4000,0.07678,M

In [31]:
data.isna().sum()

radius_mean                0
perimeter_mean             0
area_mean                  0
concavity_mean             0
concave points_mean        0
fractal_dimension_mean     0
radius_worst               0
perimeter_worst            0
area_worst                 0
concavity_worst            0
fractal_dimension_worst    0
diagnosis                  0
dtype: int64

In [32]:
data.duplicated().sum()

np.int64(0)

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   radius_mean              569 non-null    float64
 1   perimeter_mean           569 non-null    float64
 2   area_mean                569 non-null    float64
 3   concavity_mean           569 non-null    float64
 4   concave points_mean      569 non-null    float64
 5   fractal_dimension_mean   569 non-null    float64
 6   radius_worst             569 non-null    float64
 7   perimeter_worst          569 non-null    float64
 8   area_worst               569 non-null    float64
 9   concavity_worst          569 non-null    float64
 10  fractal_dimension_worst  569 non-null    float64
 11  diagnosis                569 non-null    object
dtypes: float64(11), object(1)
memory usage: 53.5+ KB

In [34]:
ind= data.iloc[:,:-1]
dep=data['diagnosis'].map({'M':1,'B':0})
print(ind.shape,dep.shape)

(569, 11) (569,)

In [35]:
ind_train,ind_test,dep_train,dep_test=train_test_split(ind,dep,test_size=0.20,random_state=38)
print(ind_train.shape,dep_train.shape,ind_test.shape,dep_test.shape)

(455, 11) (455,) (114, 11) (114,)

In [36]:
sc=StandardScaler()
ind_train=sc.fit_transform(ind_train)
ind_test=sc.transform(ind_test)

In [37]:
lr = LogisticRegression()
dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
svc = SVC()
knn = KNeighborsClassifier()

In [38]:
lr.fit(ind_train, dep_train)
dt.fit(ind_train, dep_train)
rf.fit(ind_train, dep_train)
svc.fit(ind_train, dep_train)
knn.fit(ind_train, dep_train)

KNeighborsClassifier()

In [39]:
models={
    "LogisticRegression":lr,
        "Decision Tree":dt,
        "Random Forest":rf,
        "SVC":svc,
        "KNN":knn
        }
results = {}
trained_models = {}

for name, model in models.items():
    model.fit(ind_train, dep_train)
    trained_models[name] = model
    
    pred = model.predict(ind_test)
    acc = accuracy_score(dep_test, pred)
    results[name] = acc
    
    print(f"{name} Accuracy:", acc)
    
best_algo = max(results, key=results.get)
best_model = trained_models[best_algo]

print("\nBest Algorithm:", best_algo)
print("Best Accuracy:", results[best_algo])

LogisticRegression Accuracy: 0.9473684210526315
Decision Tree Accuracy: 0.9824561403508771
Random Forest Accuracy: 0.9736842105263158
SVC Accuracy: 0.9473684210526315
KNN Accuracy: 0.9298245614035088

Best Algorithm: Decision Tree
Best Accuracy: 0.9824561403508771

In [40]:
data.columns

Index(['radius_mean', 'perimeter_mean', 'area_mean', 'concavity_mean',
       'concave points_mean', 'fractal_dimension_mean', 'radius_worst',
       'perimeter_worst', 'area_worst', 'concavity_worst',
       'fractal_dimension_worst', 'diagnosis'],
      dtype='object')

In [41]:
radius_mean = float(input("Enter radius_mean: "))
perimeter_mean = float(input("Enter perimeter_mean: "))
area_mean = float(input("Enter area_mean: "))
concavity_mean = float(input("Enter concavity_mean: "))
concave_points_mean = float(input("Enter concave points_mean: "))
fractal_dimension_mean = float(input("Enter fractal_dimension_mean: "))
radius_worst = float(input("Enter radius_worst: "))
perimeter_worst = float(input("Enter perimeter_worst: "))
area_worst = float(input("Enter area_worst: "))
concavity_worst = float(input("Enter concavity_worst: "))
fractal_dimension_worst = float(input("Enter fractal_dimension_worst: "))

user_data = np.array([[
radius_mean,
perimeter_mean, 
area_mean,
concavity_mean, 
concave_points_mean, 
fractal_dimension_mean,
radius_worst, 
perimeter_worst, 
area_worst,
concavity_worst, 
fractal_dimension_worst
]])

user_data = sc.transform(user_data)

pred = best_model.predict(user_data)

if pred[0] == 1:
    print("\nResult: Malignant (Cancer Detected)")
else:
    print("\nResult: Benign (No Cancer)")

Result: Malignant (Cancer Detected)

c:\Software\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [42]:
import pickle

pickle.dump(trained_models, open("breast_model.pkl1", "wb"))

with open("best_algorithm.txt", "w") as f:
    f.write(best_algo)